
package com.epam.lab.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapUserService", targetNamespace = "http://soap.service.lab.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapUserService {


    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns com.epam.lab.service.soap.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.AuthenticateResponse")
    public SoapResponse authenticate(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param role
     * @param userName
     * @return
     *     returns com.epam.lab.service.soap.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsersByRole", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.GetUsersByRole")
    @ResponseWrapper(localName = "getUsersByRoleResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.GetUsersByRoleResponse")
    public SoapResponse getUsersByRole(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "role", targetNamespace = "")
        String role);

    /**
     * 
     * @param password
     * @param name
     * @param userName
     * @return
     *     returns com.epam.lab.service.soap.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.DeleteUserResponse")
    public SoapResponse deleteUser(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns com.epam.lab.service.soap.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.GetAllUsersResponse")
    public SoapResponse getAllUsers(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns com.epam.lab.service.soap.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorize", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Authorize")
    @ResponseWrapper(localName = "authorizeResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.AuthorizeResponse")
    public SoapResponse authorize(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
